### ISSUE TITLE
Clip feature is not existed

### ISSUE THREAD

**Issue by Alqatf** [lezhang7/MOQAGPT#1]
Hi,
Thanks for providing us with the code for your great work.

I could not access https://drive.usercontent.google.com/download?id=15RzG-KL7EwmerV2nTzJKSprODki_3rbf&authuser=0 for download the clip features. Can you provide me with a link that can be accessed? Thanks in advance.

**Comment by lezhang7** [comment]
Hi,

Thanks for your interest in our work. The issue root in the bug of gdown. To fix it, simply update gdown by running `pip install --upgrade --no-cache-dir gdown `, and run the download script should work now, please let me know if you have further quetion.

Best

**Comment by Alqatf** [comment]
Thanks a lot for your quick response. As you suggested, the command is run, and the download script is as well. The dataset and table features were downloaded, but the clip features did not download. The error message requires checking the connection and permissions.  Also, I tried to use the brower to download as you see down:
![error](https://github.com/lezhang7/MOQAGPT/assets/33346753/07d0f9db-f990-440b-afb9-2207a3ca928f)

**Comment by lezhang7** [comment]
Previous links was pointed to the google drive folder, so it's not valid. I have fixed the bug by pointing to correct files. Git pull and  it should work now

**Comment by Alqatf** [comment]
> Previous links was pointed to the google drive folder, so it's not valid. I have fixed the bug by pointing to correct files. Git pull and it should work now

Thanks so much. It works now.
